### ISSUE TITLE
Claude 2 produce same result when temperature is 1

### ISSUE THREAD

**Issue by Qianli123** [aws-samples/amazon-bedrock-workshop#102]
By instruction, when the temperature is 1, the Claude model should produce different response to the same prompt on different API calls. But when i set temperature to 1, the model always produce the same response. Is this specifically designed or there is a configuration error?

**Comment by RoiTabach** [comment]
I have encountered the same issue with tempertures (e.g) 0,6, 0.8, 1.

It could also mean there's a cache at some level (AWS or Claude)

I have tried to reproduce in the [AWS Bedrock Text Playground](https://us-east-1.console.aws.amazon.com/bedrock/home?region=us-east-1#/text-playground), but in the Playground the answers did come out different in each time.

**Comment by w601sxs** [comment]
Closing this; please refer to the latest bedrock workshop update and reopen if still relevant
