### ISSUE TITLE
Avoid generating stereotypes.

### ISSUE THREAD

**Issue by antara678** [aws-samples/amazon-bedrock-workshop#111]
The set-up notebook needs to be improved with the prompt given to the model in [bedrock_boto3_setup.ipynb](https://github.com/aws-samples/amazon-bedrock-workshop/blob/main/00_Intro/bedrock_boto3_setup.ipynb) notebook.

There is an error displayed when calling the **Stability Stable Diffusion XL Model**, where the prompt `prompt_data = "a fine image of an astronaut riding a horse on Mars"` sometimes produces the error  ⚠️  _Sorry, this model is designed to avoid generating stereotypes. Please see our content limitations page for more information. People of different identities ride horses. ⚠️_

The prompt for the model should be updated to something more unobtrusive to avoid this error like `prompt_data = "a landscape with trees"`

**Comment by w601sxs** [comment]
Closing this; please refer to the latest bedrock workshop update and reopen if still relevant
