### ISSUE TITLE
invoke model errors / 00_generate_w_bedrock.ipynb

### ISSUE THREAD

**Issue by gcube9** [aws-samples/amazon-bedrock-workshop#116]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[21], line 8
      4 outputText = "\n"
      6 try:
----> 8     response = boto3_bedrock.invoke_model(body=body, modelId=modelId, accept=accept, contentType=contentType)
      9     response_body = json.loads(response.get("body").read())
     11     outputText = response_body.get('results')[0].get('outputText')

File /opt/conda/lib/python3.10/site-packages/botocore/client.py:888, in BaseClient.__getattr__(self, item)
    885 if event_response is not None:
    886     return event_response
--> 888 raise AttributeError(
    889     f"'{self.__class__.__name__}' object has no attribute '{item}'"
    890 )

AttributeError: 'Bedrock' object has no attribute 'invoke_model'

**Comment by GovindS22016** [comment]
are you running the workshop in SageMaker studio? if so, you need to add the bedrock permissions to the SageMaker execution role. If you are running in your own laptop, ensure your user/role has the right permissions by updating the code in the first cell.

**Comment by adnanrizve** [comment]
Make sure to set runtime= True in the [setup script](https://github.com/aws-samples/amazon-bedrock-workshop/blob/main/00_Intro/bedrock_boto3_setup.ipynb) and try to run the commands which involve Invoke operations

boto3_bedrock = bedrock.get_bedrock_client(
    assumed_role=os.environ.get("BEDROCK_ASSUME_ROLE", None),
    region=os.environ.get("AWS_DEFAULT_REGION", None),
    runtime=False
)

**Comment by w601sxs** [comment]
Closing this; please refer to the latest bedrock workshop update and reopen if still relevant
