### ISSUE TITLE
Error Cell 22 / 00_generate_w_bedrock.ipynb

### ISSUE THREAD

**Issue by gcube9** [aws-samples/amazon-bedrock-workshop#117]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[22], line 4
      1 output = []
      2 try:
----> 4     response = boto3_bedrock.invoke_model_with_response_stream(body=body, modelId=modelId, accept=accept, contentType=contentType)
      5     stream = response.get('body')
      7     i = 1

File /opt/conda/lib/python3.10/site-packages/botocore/client.py:888, in BaseClient.__getattr__(self, item)
    885 if event_response is not None:
    886     return event_response
--> 888 raise AttributeError(
    889     f"'{self.__class__.__name__}' object has no attribute '{item}'"
    890 )

AttributeError: 'Bedrock' object has no attribute 'invoke_model_with_response_stream'

**Comment by w601sxs** [comment]
Closing this; please refer to the latest bedrock workshop update and reopen if still relevant
