### ISSUE TITLE
No explanation about how to pass in the customized Bedrock endpoint URL in 09_Guardrails notebook

### ISSUE THREAD

**Issue by hinfsynz** [aws-samples/amazon-bedrock-workshop#125]
Unlike other notebooks which shows how to pass a customized Bedrock boto3 client to the Bedrock class init function as an argument, the sample notebook for 09_Guardrail only invoke a singleton class BedrockBorgModels which seems only takes no argument. This made it unable to use dev/test endpoint.

**Comment by harelix** [comment]
Good catch! You’re totally right about the inconsistency with the 09_Guardrail notebook. Funny enough, I was already tinkering with a fix for this. I plan to roll it out in the next release in a couple of days. With the fix, you’ll be able to pass a customized boto3 client just like in the other notebooks, making it easier to use dev/test endpoints.

I’ll drop a message here once the updated version is live. Thanks a bunch for pointing this out!

**Comment by harelix** [comment]
#128

**Comment by w601sxs** [comment]
Closing this; please refer to the latest bedrock workshop update and reopen if still relevant
