### ISSUE TITLE
vectorstore_faiss.similarity_search_with_score 

### ISSUE THREAD

**Issue by mansourshams** [aws-samples/amazon-bedrock-workshop#130]
Hello,

Thank you for the great workshop. In one of the notebooks, we have vectorstore_faiss.similarity_search_by_vector and I am interested to use vectorstore_faiss.similarity_search_with_score and contrary to the documentation, the scores are well outside the [0,1] range. 

My goal is to find all documents that are closely associated with a query, say score about 0.8

I would appreciate your guidance.

**Comment by w601sxs** [comment]
threshold by score?
