### ISSUE TITLE
How to truncate text for Titan-Embeddings

### ISSUE THREAD

**Issue by nabsabraham** [aws-samples/amazon-bedrock-workshop#136]
I have longer documents I want to compute embeddings for. I haven't found the setting to truncate my input to get the embedding for it because the full text errors with: 
```
ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: 400 Bad Request: Too many input tokens. Max input tokens: 8192, request input token count: 9875 
```
Can someone link me the recommended approach to truncate and embed with Titan?

**Comment by w601sxs** [comment]
Closing this; please refer to the latest bedrock workshop update and reopen if still relevant

**Comment by madelinechantry** [comment]
Can someone share the link or solution?

**Comment by yuye-aws** [comment]
Hi @w601sxs , can you share the solution to this issue?
