### ISSUE TITLE
Add examples using Meta's Llama 2 model

### ISSUE THREAD

**Issue by lovaarte** [aws-samples/amazon-bedrock-workshop#140]
Now that Meta's Llama 2 Chat 13B model is available, it would be great to add labs using this model.

**Comment by aarora79** [comment]
+1, would be great to add examples for Llama2.

**Comment by lovaarte** [comment]
Update: 
There is dependency for Langchain to support Llama2 on Bedrock.
Langchain open issue describing the issue: https://github.com/langchain-ai/langchain/issues/13316
Langchain proposed fix: https://github.com/aws-samples/aws-genai-llm-chatbot/pull/221

**Comment by laolongju** [comment]
+1, would be great to add examples for Llama2.

**Comment by w601sxs** [comment]
Closing this; please refer to the latest bedrock workshop update and reopen if still relevant
