### ISSUE TITLE
Add example of Image Outpaiting with Stable Diffusion

### ISSUE THREAD

**Issue by ddzmitry** [aws-samples/amazon-bedrock-workshop#141]
Currently there is an example of image in-painting , it would be amazing to have an example of extending image using Stable Diffusion.

**Comment by kai-zhu-aws** [comment]
As far as I know, there is no outpainting for Stable Diffusion in Bedrock Developer guide https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-stability-diffusion.html.

I can see outpainting example code for Titan image models https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-titan-image.html
