### ISSUE TITLE
missing policies for 02_qa_w_rag_claude_opensearch.ipynb

### ISSUE THREAD

**Issue by saidnech** [aws-samples/amazon-bedrock-workshop#143]
I had to add the following policies to get 02_qa_w_rag_claude_opensearch.ipynb working

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "iam:CreateServiceLinkedRole",
            "Resource": "*"
        }
    ]
}

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "aoss:*",
            "Resource": "*"
        }
    ]
}

**Comment by w601sxs** [comment]
Closing this; please refer to the latest bedrock workshop update and reopen if still relevant
