### ISSUE TITLE
00_Intro bedrock_boto3_setup.ipynb has an error setting up dependencies.

### ISSUE THREAD

**Issue by ken5scal** [aws-samples/amazon-bedrock-workshop#147]
Under  Amazon SageMaker Studio Classic with Data Science 2.0/3.0, installation of dependencies always stops at the following step. I have tried to fix dependencies manually, but it wasn't feasible.

# step
```
pip install --no-build-isolation --force-reinstall \
    "boto3>=1.28.57" \
    "awscli>=1.29.57" \
    "botocore>=1.31.57"
```

# result
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
(bunch of dependencies)
```

**Comment by GovindS22016** [comment]
You can safely ignore those dependency errors. You will see a message after the errors stating that it successfully installed boto3, cli, etc.

**Comment by w601sxs** [comment]
Closing this; please refer to the latest bedrock workshop update and reopen if still relevant
