### ISSUE TITLE
Cannot create pinecone index

### ISSUE THREAD

**Issue by govin-pal** [aws-samples/amazon-bedrock-workshop#160]
Inside 03_QuestionAnswering/02_rag_claude_titan_pinecone.ipynb, the cell that creates the pinecone index throws this error: 
MaxRetryError: HTTPSConnectionPool(host='controller.your_env.pinecone.io', port=443): Max retries exceeded with url: /databases (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1b66682a10>: Failed to resolve 'controller.your_env.pinecone.io' ([Errno -2] Name or service not known)"))

**Comment by nibrahv** [comment]
It looks as if the guidance to set up the Pinecone prerequisites has been removed.  

Try logging in to Pinecone.io and setting up an API key.  Grab the API key itself and the environment (from the Pinecone console, under API Keys).  Either set this up as environment variables or hardcode them into the notebook (not best practice, but works...).  

Also, I had trouble with the index creation as well, so as a workaround manually created it and commented out the code to delete and recreate it in the notebook.

**Comment by w601sxs** [comment]
Closing this; please refer to the latest bedrock workshop update and reopen if still relevant
