### ISSUE TITLE
How do I contribute javascript version of this repo? 

### ISSUE THREAD

**Issue by pacopalo** [aws-samples/amazon-bedrock-workshop#186]
How do I contribute the javascript version of this repo?  Any suggestion where to put the code?

**Comment by rppth** [comment]
Hey please send me a note with more details at rppth@amazon.com, we can worth through this!

**Comment by w601sxs** [comment]
can you do a PR?

**Comment by pacozaa** [comment]
@w601sxs sure!

**Comment by w601sxs** [comment]
Will close for now and you can mention this ticket when you get some time.
