### ISSUE TITLE
pysqlite3 is not installable from osx.

### ISSUE THREAD

**Issue by wangmir** [aws-samples/amazon-bedrock-workshop#188]
Please check this: https://github.com/coleifer/pysqlite3/issues/1

Because, in case of OSX, default OSX does not allow extension, pysqlite3 cannot be installable from osx.

But, in here https://github.com/aws-samples/amazon-bedrock-workshop/blob/main/00_Intro/bedrock_boto3_setup.ipynb
procedure includes installation of pysqlite3, and it makes impossible to proceed from osx.

**Comment by w601sxs** [comment]
Closing this; please refer to the latest bedrock workshop update and reopen if still relevant.
