### ISSUE TITLE
Python 3.7 is no longer supported for for creating or updating Lambda function  

### ISSUE THREAD

**Issue by aemamz** [aws-samples/amazon-bedrock-workshop#195]
Error while running the cloud formation template while creating the DefaultVpcLambda showing that python 3.7 is no longer supported and upgrade needed to 3.12, cloud formation template needs to be updated.

**Comment by w601sxs** [comment]
hi, which notebook was this in? can you link to the latest workshop commit and/or see if it still exists? Please reopen if it does
