### ISSUE TITLE
How to access Code Llama using AWS Bedrock?

### ISSUE THREAD

**Issue by code-rex1** [aws-samples/amazon-bedrock-workshop#202]
I'm having difficulty understanding the process of accessing Code Llama using AWS Bedrock. 

Could someone please provide detailed instructions or documentation on how to accomplish this task? 

Any assistance would be greatly appreciated. Thank you!

**Comment by w601sxs** [comment]
please check https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html

**Comment by yaci** [comment]
This issue ranks high in Google for `how to access llama in amazon bedrock` so a hint for future visitors who cannot find it in Bedrock's console: not all models are available in all regions. Your best bet is to change region to  Oregon, `us-west-2` and request access to llama from there.
