### ISSUE TITLE
Broken Link in workshop documentation https://catalog.us-east-1.prod.workshops.aws/workshops/a4bdb007-5600-4368-81c5-ff5b4154f518/en-US

### ISSUE THREAD

**Issue by rimonm** [aws-samples/amazon-bedrock-workshop#205]
Links to notebooks in the workshop content (workshops.aws) are now broken due to folder structure changes.

Workshop link: https://catalog.us-east-1.prod.workshops.aws/workshops/a4bdb007-5600-4368-81c5-ff5b4154f518/en-US

Examples:
1/Page: Environment Setup
Links: bedrock_boto3_setup.ipynb 

2/Page: Text Generation with a Simple Prompt
Links:  01_Generation/00_generate_w_bedrock.ipynb
 01_Generation/01_zero_shot_generation.ipynb

**Comment by rsgrewal-aws** [comment]
Please use the latest build -- and published public link -- 1/ was working ok 2/ was broken and has been fixed
