### ISSUE TITLE
Broken link to execute Agents in Bedrock

### ISSUE THREAD

**Issue by acloud360** [aws-samples/amazon-bedrock-workshop#206]
Following link is broken, please fix this one:

https://github.com/aws-samples/amazon-bedrock-workshop/blob/main/07_Agents/customer_service_agent/customer_service_agent_openapi_schema.json

**Comment by acloud360** [comment]
on similar lines, following link/s are broken as well:
07_Agents/customer_service_agent/customer_service_agent_sqlite_db

**Comment by rsgrewal-aws** [comment]
can you test with the latest build -- the readme links seemed to work for the main file
