### ISSUE TITLE
Amazon Bedrock Workshop - Citation for Facebook Research

### ISSUE THREAD

**Issue by chainhead** [aws-samples/amazon-bedrock-workshop#232]
**Describe the bug**

The following statement is in `01_Text_generation/03_qa_with_bedrock_titan.ipynb`. Can you please provide a citation for the same?

> Research by Facebook in 2020 found that LLM knowledge could be augmented on the fly by providing the additional knowledge base as part of the prompt. This approach is called Retrieval Augmented Generation, or RAG.

**To Reproduce**
Steps to reproduce the behavior (or some version of this):
Walk through `01_Text_generation/03_qa_with_bedrock_titan.ipynb`.

**Expected behavior**
Citation provided.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
Not applicable.

**Smartphone (please complete the following information):**
Not applicable.

**! Additional context !**
Not applicable.

**Comment by codekiln** [comment]
@chainhead maybe https://research.facebook.com/file/4283170945104179/Retrieval-Augmented-Generation-for-Knowledge-Intensive-NLP-Tasks.pdf

**Comment by w601sxs** [comment]
Added thanks @chainhead
