### ISSUE TITLE
Invalid URL in download-dependencies.sh

### ISSUE THREAD

**Issue by carlo-aps-group** [aws-samples/amazon-bedrock-workshop#27]
Hi, 

There is an issue while executing the `download-dependencies.sh`[1] file. When executing this file curl fails because the URL `https://preview.documentation.bedrock.aws.dev/Documentation/SDK/bedrock-python-sdk.zip cannot be resolved. 

[1]: https://github.com/aws-samples/amazon-bedrock-workshop/blob/3c12ea81130e5dd0ba53286ad75fe15cc75755f3/download-dependencies.sh

**Comment by rstrahan** [comment]
This was fixed two weeks ago in commit [59397cad2f4e6a4ead8012a87fc43ec977401698](https://github.com/aws-samples/amazon-bedrock-workshop/commit/59397cad2f4e6a4ead8012a87fc43ec977401698)
Can you check that you are in main branch and have pulled the latest commit?
Tx.
