### ISSUE TITLE
Recommend adding "Enable Model access" to the README instructions

### ISSUE THREAD

**Issue by teharris1** [aws-samples/amazon-bedrock-workshop#284]
**Describe the bug**
I believe this is a repeat of the issue #87, however, that issue was closed and does not appear to have been resolved. 

When using the workshop for the first time on an account that has never used Bedrock before the error appears when invoking cell `Amazon Titan Text Premier` in the `bedrock_basics.ipynb` notebook: 
```
You don't have access to the model with the specified model ID.                
To troubeshoot this issue please refer to the following resources.                 
https://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot_access-denied.html                 
https://docs.aws.amazon.com/bedrock/latest/userguide/security-iam.html
```

**To Reproduce**
Steps to reproduce the behavior (or some version of this):
1. Start in an account with no model access provided
2. Follow the `Getting Started` instructions
3. Test the setup using the `bedrock_basics.ipynb` notebook
4. See error in the output of the `Amazon Titan Text Premier` cell

**Expected behavior**
The `Getting Started` section should reference the directions on how to enable model access such as:
https://docs.aws.amazon.com/bedrock/latest/userguide/model-access.html#add-model-access

**Screenshots**

**Desktop (please complete the following information):**
 - OS: NA
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**

**! Additional context !**
- Visual Studio Code with Jupyter notebook
- SSO enabled on account 
- AdministratorAccess role used
- Notebook cloned 8/15/2024

**Comment by w601sxs** [comment]
Thanks!

I added:

This code goes alongside the self-paced or instructor lead workshop here - https://catalog.us-east-1.prod.workshops.aws/amazon-bedrock/en-US

**Please follow the prerequisites listed in the link above or ask your AWS workshop instructor how to get started.**
