### ISSUE TITLE
Bedrock streaming example improvement.

### ISSUE THREAD

**Issue by jwdinkel** [aws-samples/amazon-bedrock-workshop#35]
https://github.com/aws-samples/amazon-bedrock-workshop/blob/main/00_Intro/bedrock_boto3_setup.ipynb

The Streaming example had two issues that can easily be corrected if you wish.
1) It was using a prompt from the previous cell which caused an error.
2) It doesn't include all the parameter tuning so it cuts off the response and yields a pretty poor example of streaming.

Here's a video of the corrections:

https://github.com/aws-samples/amazon-bedrock-workshop/assets/7911734/e1cae26a-c9a4-4cb7-9586-eb309a114db6

Code shown in video that works:

```python
#The prompt was not here. I added it because the prompt above was giving me warnings
# when I used this prompt that was carried from the previous image example.
#prompt_data = "a fine image of an astronaut riding a horse on Mars"
prompt_data = "Write me a story about red riding hood"
from IPython.display import clear_output, display, display_markdown, Markdown

# I am replacing this body so that it doesn't cut off the results. I've added the textGenerationConfig code so the response can be tuned.
body = json.dumps({
    "inputText": prompt_data, 
    "textGenerationConfig":{
        "maxTokenCount":4096,
        "stopSequences":[],
        "temperature":0,
        "topP":0.9
        }
    }) 


#body = json.dumps({"inputText": prompt_data})
modelId = "amazon.titan-tg1-large"  # (Change this, and the request body, to try different models)
accept = "application/json"
contentType = "application/json"

response = boto3_bedrock.invoke_model_with_response_stream(
    body=body, modelId=modelId, accept=accept, contentType=contentType
)
stream = response.get('body')
output = []

if stream:
    for event in stream:
        chunk = event.get('chunk')
        if chunk:
            chunk_obj = json.loads(chunk.get('bytes').decode())
            text = chunk_obj['outputText']
            clear_output(wait=True)
            output.append(text)
            display_markdown(Markdown(''.join(output)))
```

**Comment by rppth** [comment]
This looks cool mind cutting a PR so we can review/Merge!

**Comment by jwdinkel** [comment]
> This looks cool mind cutting a PR so we can review/Merge!

I do not have a local editor for ipnyb files and gitHub doesn't seem to offer an online editor that removes the abstraction of all the notebook syntax.

Feel free to simply replace the code I provided with your code whenever you update the repo in the future. No need to give credit.

**Comment by jwdinkel** [comment]
I realized that Google Colab allows me to use File | Save to GitHub and handles the authentication easily, sends me directly to the commit of my fork and then lets me create the pull request on the commit.

You're welcome. But I still think GitHub should have a built-in editor for notebooks. Thanks to Google for making this edit easy, otherwise, I wouldn't have taken the time.

**Comment by krrishdholakia** [comment]
Hey @jwdinkel, 

another way you could run streaming with Bedrock (w/ consistent params) is through LiteLLM: 

```python
import os 
from litellm import completion

os.environ["AWS_ACCESS_KEY_ID"] = ""
os.environ["AWS_SECRET_ACCESS_KEY"] = ""
os.environ["AWS_REGION_NAME"] = ""

response = completion(
            model="anthropic.claude-instant-v1", 
            messages=[{ "content": "Hello, how are you?","role": "user"}],
           max_tokens=4096,
           temperature=0,
           top_p=0.9
)
```

**Comment by w601sxs** [comment]
Closing this; please refer to the latest bedrock workshop update and reopen if still relevant
