### ISSUE TITLE
Unable to Unzip Files on Sagemaker Notebook - Missing Unzip Command for dependencies bash script

### ISSUE THREAD

**Issue by Pauldevillers** [aws-samples/amazon-bedrock-workshop#4]
**Issue Description:**
I encountered a problem while trying to run a bash script on my Sagemaker notebook instance. The script ``download-dependencies.sh`` relies on the unzip command to extract files, but it appears that the unzip command is not installed on the Sagemaker notebook environment. As a result, the bash script fails to execute successfully.

**Steps to Reproduce:**

1. Launch a Sagemaker notebook instance.
2. Upload or create a bash script that includes the unzip command to extract files.
3. Attempt to run the bash script using the Sagemaker notebook terminal.

**Proposed Solution:**

Run command before unzip : ``sudo yum install unzip``

**Comment by rppth** [comment]
This Issue should be solved by #8
