### ISSUE TITLE
Why can't I find the list_foundation_models method

### ISSUE THREAD

**Issue by MrShao233** [aws-samples/amazon-bedrock-workshop#44]
<img width="893" alt="image" src="https://github.com/aws-samples/amazon-bedrock-workshop/assets/39620279/7875ac1e-9693-4145-98f5-5bb23d409725">
I can't find the method

**Comment by lauerarnaud** [comment]
@MrShao233 what error are you getting?  Are you able to clone the latest version of the repo and try again?  Please make sure you upgrade to the latest boto3 SDK to use the right boto3 clients.

**Comment by lauerarnaud** [comment]
Please try again with latest version of repo and SDK now that Amazon Bedrock has gone GA (there are now two new clients bedrock and bedrock-runtime).
