### ISSUE TITLE
01_qa_w_rag_claude Throws Error Creating and Populating VectorDB

### ISSUE THREAD

**Issue by shane-thompson** [aws-samples/amazon-bedrock-workshop#59]
When I create a default brand new user in Sagemaker Studio and run this notebook (with the latest langchain changes) I get the error below.  Upgrading SQLalchemy as part of the dependency installation seems to fix this.  I'm not sure that this is the right fix though and there is actually a newer version of langchain as of today (3.0.5) but even running that version of langchain in the dependency install results in the same error.  

<img width="755" alt="Screenshot 2023-09-29 at 6 10 11 PM" src="https://github.com/aws-samples/amazon-bedrock-workshop/assets/50842283/815eec63-e958-4d66-9ec8-8e11a48658ef">

**Comment by lauerarnaud** [comment]
Closing as updates merged.
