### ISSUE TITLE
Lab 03 - Workshop 01 qa_rag_claude

### ISSUE THREAD

**Issue by MarcCCreposAWS** [aws-samples/amazon-bedrock-workshop#67]
The modelID used in the embedding is "amazon.titan-embed-g1-text-02", which results in the "AccessDeniedException" error. Based on the Bedrock user guide, they recommend using the naming: "amazon.titan-embed-text-v1". After using this modelID, everything works fine.

**Comment by lauerarnaud** [comment]
Thanks @MarcCCreposAWS PR in progress for this. https://github.com/aws-samples/amazon-bedrock-workshop/pull/81
