### ISSUE TITLE
Broken link to download-dependencies.sh in bedrock_boto3_setup notebook

### ISSUE THREAD

**Issue by WW5JS** [aws-samples/amazon-bedrock-workshop#68]
In [bedrock_boto3_setup](https://github.com/aws-samples/amazon-bedrock-workshop/blob/main/00_Intro/bedrock_boto3_setup.ipynb) under Prerequisites the link to [download-dependencies.sh](https://github.com/aws-samples/amazon-bedrock-workshop/blob/79abc9d3f4c50d0266c8990cd229e8ca145c0be8/download-dependencies.sh) is broken.

**Comment by WW5JS** [comment]
<img width="1430" alt="image" src="https://github.com/aws-samples/amazon-bedrock-workshop/assets/28718463/6b7f42c6-55fe-48b0-9188-b089fd68d1c2">

**Comment by rafalbog** [comment]
I also see thta it was removed, I have it already downloaded and lambda layers prepared, but it would be nice to get the information about the steps to intall all the dependencies, and does the botocore  have the bedrock service added in docs

**Comment by jld23** [comment]
@rafalbog Boto3 1.28.57 and higher have the bedrock clients (`bedrock` and `bedrock-runtime`). If you want to use Bedrock with lambda you'll need to use a lambda layer until boto3 is revised to a version higher than 1.28.57. [Here is an example](https://github.com/aws-samples/amazon-bedrock-samples/tree/main/generative-ai-solutions/bedrock-lambda-layer)
