### ISSUE TITLE
Amazon Titan Large example does not work

### ISSUE THREAD

**Issue by jicowan** [aws-samples/amazon-bedrock-workshop#71]
When you run the Amazon Titan Large example in the bedrock_boto3_setup.ipynb notebook, you get the following error: 

```
AccessDeniedException: An error occurred (AccessDeniedException) when calling the InvokeModel operation: Your account is not authorized to invoke this API operation.
```

**Comment by jicowan** [comment]
None of the Titan examples in bedrock_boto3_setup.ipynb notebook work.

**Comment by lauerarnaud** [comment]
Titan Text Express is still in preview at the moment, so you will receive this error unless you have access to the private preview of the model.
