### ISSUE TITLE
Undefined variable in 03_QuestionAnswering/02_qa_w_rag_claude_pinecone.ipynb

### ISSUE THREAD

**Issue by seansummers** [aws-samples/amazon-bedrock-workshop#73]
`data` is undefined, making the notebook impossible to continue executing:

![image](https://github.com/aws-samples/amazon-bedrock-workshop/assets/165854/c3c51954-8082-42f5-81d0-ed6fd94c013f)

**Comment by ari-in-media-res** [comment]
Thanks for the review. Updated the notebook and created [PR](https://github.com/aws-samples/amazon-bedrock-workshop/pull/76)

**Comment by hf-qin** [comment]
The bug is not fixed yet.

**Comment by ari-in-media-res** [comment]
This should be resolved in the latest PR of this notebook:
https://github.com/aws-samples/amazon-bedrock-workshop/pull/92

**Comment by lauerarnaud** [comment]
PR merged.
