### ISSUE TITLE
Importing PromptTemplate from langchain root module is no longer supported

### ISSUE THREAD

**Issue by kuriaks1** [aws-samples/amazon-bedrock-workshop#75]
Executing cell 4 on notebook 02_contextual_generation.ipynb throws the warning "Importing PromptTemplate from langchain root module is no longer supported". Replacing the line "from langchain import PromptTemplate" to "from langchain.prompts import PromptTemplate" to fix the issue.

![Screenshot 2023-10-05 at 11 01 54 AM](https://github.com/aws-samples/amazon-bedrock-workshop/assets/105688567/add6174d-683e-4859-b758-7444749c4892)

**Comment by alkayahan** [comment]
https://github.com/aws-samples/amazon-bedrock-workshop/pull/62
