### ISSUE TITLE
Add instructions in readme.md to enable models before starting

### ISSUE THREAD

**Issue by mostlyrobots** [aws-samples/amazon-bedrock-workshop#87]
When running the tutorial on a new account that has not been set up, API calls will return "AccessDenied" errors for models that need access added:

Add links to https://docs.aws.amazon.com/bedrock/latest/userguide/setting-up.html and https://docs.aws.amazon.com/bedrock/latest/userguide/model-access.html to readme.md intro

**Comment by w601sxs** [comment]
Closing this; please refer to the latest bedrock workshop update and reopen if still relevant
