### ISSUE TITLE
Streaming Inference Error

### ISSUE THREAD

**Issue by RamVegiraju** [aws-samples/amazon-bedrock-workshop#88]
In the intro notebook 00_Intro: bedrock_boto3_setup.ipynb the streaming inference portion is broken. The following code:

```
 if chunk:
                chunk_obj = json.loads(chunk.get('bytes').decode())
                text = chunk_obj['outputText']
```

leads to an issue, the chunk object now seems to have changed it's output format structure . This needs to be properly updated to the following:

```
if chunk:
            chunk_obj = json.loads(chunk.get('bytes').decode())
            text = chunk_obj['completion']
```

Package Versions-
Boto3 1.28.62
langchain 0.0.311

**Comment by lauerarnaud** [comment]
Thanks, please try again with new notebook post merge. https://github.com/aws-samples/amazon-bedrock-workshop/pull/94. There is now an example for Titan Text and Claude. In stream mode, using claude-v2, each line starts with the keyword completion and not outputText.
