### ISSUE TITLE
Incorrect Documentation in 00_Intro/bedrock_boto3_setup.ipynb

### ISSUE THREAD

**Issue by harshpas-amazon** [aws-samples/amazon-bedrock-workshop#89]
The "00_Intro/bedrock_boto3_setup.ipynb" [notebook](https://github.com/aws-samples/amazon-bedrock-workshop/blob/main/00_Intro/bedrock_boto3_setup.ipynb) still mentions that "You should already have run the [../download-dependencies.sh script](https://github.com/aws-samples/amazon-bedrock-workshop/blob/b6479a9f27fde914801c6516422ad61d269b65ed/download-dependencies.sh) to fetch the SDK packages required for using Bedrock."

The file doesn't exist anymore, and even the cell below it uses publicly available new versions of boto and botocore.

**Comment by aswin80** [comment]
yes I have observed this to be a problem, especially recently this file got removed. having said, I got this working by downloading the sdk from the url in the previous version of dependencies.sh
