### ISSUE TITLE
Pattern to store embedding to Postgres as vector store

### ISSUE THREAD

**Issue by aswin80** [aws-samples/amazon-bedrock-workshop#97]
A pattern that demonstrates, storing text as embedded values in a vector store and  using this for RAG to retrieve relevant information will be a useful pattern to have. This will be a common use case in Q&A and slo when it comes to summarizing large corpus

**Comment by w601sxs** [comment]
Closing this; please refer to the latest bedrock workshop update and reopen if still relevant
